############ data access ############ 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev
    username: 
    password: 

############ custom ############     
custom:
  datasource:
    driverClassName: com.mysql.jdbc.Driver