########### eureka ###########
#eureka:
#  client:
#    serviceUrl:
##      defaultZone: https://ll-cloud-comedic-cassowary.cfapps.io/eureka-server/eureka/
#      defaultZone: http://localhost:8761/eureka/
#    healthcheck:
#      enabled: true

cloudms:
  discovery:
    auto-config:
      enabled: true
      defaultZone: http://localhost:8761/eureka-server-0.0.1/eureka