########### server ###########  
server:
  port: 8091

########### logging ########### 
logging:
  level:
    root: WARN 
    org:
      AuthenticateServer: DEBUG
      springframework:
        security: DEBUG
        web: DEBUG


########### eureka ###########
# found in config server common config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

########### api ###########     
api:
  resourceID: sparklr
  client: api_client
  secret: secret
  grantType: password
  
  
########### security ###########
security:
  storeType: JKS
  trustStore: jks/oauth.jks
  storepass: 
  trustKeyAlias: rsaauthkey
  sigAlg: SHA256withRSA


########### spring ########### 
spring:
  profiles:
    active: cloud
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQLDialect
#      dialect: org.hibernate.dialect.Oracle10gDialect
      packagesToScan: org.business.models