########### server ###########  
server:
  port: 8090

########### logging ########### 
logging:
  level:
    root: WARN 
    org:
      ll: DEBUG
      springframework:
        security: DEBUG
        web: DEBUG
        
########### zuul ###########   
zuul:
  routes:
    api:
      path: /api/**
      serviceId: api
      sensitiveHeaders: 
  host:
    maxTotalConnections: 200
    maxPerRouteConnections: 100

########### ribbon ###########  
ribbon:
  eureka:
    enabled: true

########### eureka ###########
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      

########### security ###########
security:
  storeType: JKS
  trustStore: jks/clientTrust.jks
  storepass: clientTrust
  trustKeyAlias: rsaauthKey
  sigAlg: SHA256withRSA
  resourceID: sparklr
  