server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    
spring:
  cloud:
    config:
      url: http://localhost:8888

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF