############ data access ############ 
spring:
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQLDialect
#      dialect: org.hibernate.dialect.Oracle10gDialect
      packagesToScan: org.business.models
      
  datasource:
    url: jdbc:mysql://localhost:3306/dev
    username: 
    password:  

############ custom ############     
custom:
  datasource:
    driverClassName: com.mysql.jdbc.Driver