server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        native:
          searchLocations: file:///${HOME}/git/temp-config
          
logging:
  level:
    root: info
    org.ll.auth: debug
  file: logs/config-server.log