server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: ${HOME}/git/temp-config
          refreshRate: 10

eureka:
  client:
    serviceUrl:
      defaultZone: https://ll-cloud-comedic-cassowary.cfapps.io/eureka-server/eureka/
 